import type { Member, Payment } from './definitions';

export const members: Member[] = [
  {
    id: '1',
    memberNumber: 'GF001',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    birthday: '1990-05-15',
    signupDate: '2023-01-10',
    paymentCycle: 'monthly',
    treadmillAccess: true,
    status: 'active',
    avatarUrl: 'https://picsum.photos/100/100?random=1',
  },
  {
    id: '2',
    memberNumber: 'GF002',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    birthday: '1988-08-22',
    signupDate: '2022-11-20',
    paymentCycle: 'yearly',
    treadmillAccess: false,
    status: 'active',
    avatarUrl: 'https://picsum.photos/100/100?random=2',
  },
  {
    id: '3',
    memberNumber: 'GF003',
    firstName: 'Mike',
    lastName: 'Johnson',
    email: 'mike.johnson@example.com',
    birthday: '1995-12-01',
    signupDate: '2023-03-15',
    paymentCycle: 'monthly',
    treadmillAccess: true,
    status: 'inactive',
    avatarUrl: 'https://picsum.photos/100/100?random=3',
  },
  {
    id: '4',
    memberNumber: 'GF004',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@example.com',
    birthday: '1992-07-30',
    signupDate: '2021-09-05',
    paymentCycle: 'quarterly',
    treadmillAccess: false,
    status: 'frozen',
    avatarUrl: 'https://picsum.photos/100/100?random=4',
  },
  {
    id: '5',
    memberNumber: 'GF005',
    firstName: 'Chris',
    lastName: 'Brown',
    email: 'chris.brown@example.com',
    birthday: '1985-02-18',
    signupDate: '2023-06-25',
    paymentCycle: 'monthly',
    treadmillAccess: true,
    status: 'active',
    avatarUrl: 'https://picsum.photos/100/100?random=5',
  },
];

export const payments: Payment[] = [
  {
    id: 'p1',
    memberId: '1',
    memberName: 'John Doe',
    amount: 50,
    date: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
    status: 'paid',
    memberAvatarUrl: 'https://picsum.photos/100/100?random=1',
  },
  {
    id: 'p2',
    memberId: '2',
    memberName: 'Jane Smith',
    amount: 500,
    date: new Date(new Date().setFullYear(new Date().getFullYear() - 1)).toISOString(),
    status: 'paid',
    memberAvatarUrl: 'https://picsum.photos/100/100?random=2',
  },
  {
    id: 'p3',
    memberId: '5',
    memberName: 'Chris Brown',
    amount: 50,
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    status: 'due',
    memberAvatarUrl: 'https://picsum.photos/100/100?random=5',
  },
  {
    id: 'p4',
    memberId: '1',
    memberName: 'John Doe',
    amount: 50,
    date: new Date().toISOString(),
    status: 'due',
    memberAvatarUrl: 'https://picsum.photos/100/100?random=1',
  },
    {
    id: 'p5',
    memberId: '4',
    memberName: 'Emily Davis',
    amount: 150,
    date: new Date(new Date().setDate(new Date().getDate() - 45)).toISOString(),
    status: 'overdue',
    memberAvatarUrl: 'https://picsum.photos/100/100?random=4',
  },
];
